name: Build

on:
  push:
    branches:
      - 'main'
      - 'aya-test'

jobs:
  docker-build-push:
    name: Docker build and push
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Build the Docker image first
      - uses: docker/build-push-action@v4
        with:
          push: false
          file: ./Dockerfile.polkadot
          tags: ${{ github.repository }}:latest

      # Slim it!
      - uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: ${{ github.repository }}:latest
          tag: 'slim'

      # Docker Hub Login
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Push to the registry
      - run: |
          docker tag ${{ github.repository }}:slim ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}:slim
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}:slim
