name: Build

on:
  push:
    branches:
      - 'main'
      - 'aya-test'

jobs:
  docker-build-push:
    name: Docker build and push
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: docker/build-push-action@v4
        with:
          push: false
          file: Dockerfile.polkadot
          tags: ${{secrets.DOCKERHUB_USERNAME}}/polkadot-cli:${{ github.sha }}

      - uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: ${{secrets.DOCKERHUB_USERNAME}}/polkadot-cli:${{ github.sha }}
          tag: ${{secrets.DOCKERHUB_USERNAME}}/polkadot-cli:${{ github.sha }}

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: |
          docker tag ${{secrets.DOCKERHUB_USERNAME}}/polkadot-cli:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/polkadot-cli:slim-{{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/polkadot-cli:slim-{{ github.sha }}
